// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDECCYIWQQddpJBohB6ECkuuVcmnRQ9aCE',
    appId: '1:680832435459:web:a83defc2d142e528ec5536',
    messagingSenderId: '680832435459',
    projectId: 'messenger-bba4a',
    authDomain: 'messenger-bba4a.firebaseapp.com',
    storageBucket: 'messenger-bba4a.appspot.com',
    measurementId: 'G-0RRGKY0TMY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6FOuFtxvcyXv9iRoPogWebWNUvPcUq1k',
    appId: '1:680832435459:android:6c38d50351ef8553ec5536',
    messagingSenderId: '680832435459',
    projectId: 'messenger-bba4a',
    storageBucket: 'messenger-bba4a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkit1KjaYuBXdd-mvYyhtSqEFVdciv_fM',
    appId: '1:680832435459:ios:57d6b1621cce48c4ec5536',
    messagingSenderId: '680832435459',
    projectId: 'messenger-bba4a',
    storageBucket: 'messenger-bba4a.appspot.com',
    iosClientId: '680832435459-7dvcfgs7gf3d6hq23j6koltdaf80kna9.apps.googleusercontent.com',
    iosBundleId: 'com.example.mymessenger',
  );
}
